/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.SwingFXUtils;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileView;

/**
 *
 * @author zassu
 */
public class Panel extends javax.swing.JFrame {
    
    

    private JFileChooser Buscar = new JFileChooser();
    private Toolkit t = Toolkit.getDefaultToolkit();
    private Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private int anchosc = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    private int largosc = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    public BufferedImage bfImageglobal;

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setExtendedState(NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datos = new javax.swing.JInternalFrame();
        showName = new javax.swing.JTextField();
        imgName = new javax.swing.JTextField();
        sizeShow = new javax.swing.JTextField();
        anchoImg = new javax.swing.JTextField();
        largoImg = new javax.swing.JTextField();
        showXmouse = new javax.swing.JTextField();
        posXmosue = new javax.swing.JTextField();
        showYmouse = new javax.swing.JTextField();
        posYmouse = new javax.swing.JTextField();
        showRedImg = new javax.swing.JTextField();
        valRedImg = new javax.swing.JTextField();
        showGreenImg = new javax.swing.JTextField();
        valGreenImg = new javax.swing.JTextField();
        showBlueImg = new javax.swing.JTextField();
        valBlueImg = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        actionMenuDatos = new javax.swing.JMenu();
        sizeOfImage1 = new javax.swing.JCheckBoxMenuItem();
        nameOfImage1 = new javax.swing.JCheckBoxMenuItem();
        grabberOptn1 = new javax.swing.JMenu();
        Coord1 = new javax.swing.JCheckBoxMenuItem();
        redGrabber1 = new javax.swing.JCheckBoxMenuItem();
        greenGrabber1 = new javax.swing.JCheckBoxMenuItem();
        blueGrabber1 = new javax.swing.JCheckBoxMenuItem();
        Histograma1 = new javax.swing.JMenu();
        redHist1 = new javax.swing.JCheckBoxMenuItem();
        greenHist1 = new javax.swing.JCheckBoxMenuItem();
        blueHist1 = new javax.swing.JCheckBoxMenuItem();
        labelImg = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Cargar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        Ver = new javax.swing.JMenu();
        datosWindow = new javax.swing.JMenuItem();

        Datos.setBorder(null);
        Datos.setClosable(true);
        Datos.setTitle("Datos de la Imagen");
        Datos.setVisible(true);

        showName.setEditable(false);
        showName.setText("Nombre:");
        showName.setEnabled(false);

        imgName.setEditable(false);
        imgName.setEnabled(false);

        sizeShow.setEditable(false);
        sizeShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sizeShow.setText("Tamaño");
        sizeShow.setEnabled(false);
        sizeShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeShowActionPerformed(evt);
            }
        });

        anchoImg.setEditable(false);
        anchoImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anchoImg.setEnabled(false);

        largoImg.setEditable(false);
        largoImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        largoImg.setEnabled(false);

        showXmouse.setEditable(false);
        showXmouse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showXmouse.setText("X");
        showXmouse.setEnabled(false);

        posXmosue.setEditable(false);
        posXmosue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posXmosue.setEnabled(false);

        showYmouse.setEditable(false);
        showYmouse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showYmouse.setText("Y");
        showYmouse.setEnabled(false);

        posYmouse.setEditable(false);
        posYmouse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posYmouse.setEnabled(false);

        showRedImg.setEditable(false);
        showRedImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showRedImg.setText("R");
        showRedImg.setEnabled(false);

        valRedImg.setEditable(false);
        valRedImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valRedImg.setEnabled(false);

        showGreenImg.setEditable(false);
        showGreenImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showGreenImg.setText("G");
        showGreenImg.setEnabled(false);

        valGreenImg.setEditable(false);
        valGreenImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valGreenImg.setEnabled(false);

        showBlueImg.setEditable(false);
        showBlueImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showBlueImg.setText("B");
        showBlueImg.setEnabled(false);

        valBlueImg.setEditable(false);
        valBlueImg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valBlueImg.setEnabled(false);

        actionMenuDatos.setText("Acciones");
        actionMenuDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sizeOfImage1.setText("Tamaño");
        sizeOfImage1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actionMenuDatos.add(sizeOfImage1);

        nameOfImage1.setText("Nombre");
        actionMenuDatos.add(nameOfImage1);

        grabberOptn1.setText("Grabber");

        Coord1.setText("Coordenadas");
        Coord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coord1ActionPerformed(evt);
            }
        });
        grabberOptn1.add(Coord1);

        redGrabber1.setText("Rojo");
        grabberOptn1.add(redGrabber1);

        greenGrabber1.setText("Verde");
        greenGrabber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenGrabber1ActionPerformed(evt);
            }
        });
        grabberOptn1.add(greenGrabber1);

        blueGrabber1.setText("Azul");
        grabberOptn1.add(blueGrabber1);

        actionMenuDatos.add(grabberOptn1);

        Histograma1.setText("Histograma");

        redHist1.setText("Rojo");
        Histograma1.add(redHist1);

        greenHist1.setText("Verde");
        Histograma1.add(greenHist1);

        blueHist1.setText("Azul");
        Histograma1.add(blueHist1);

        actionMenuDatos.add(Histograma1);

        jMenuBar1.add(actionMenuDatos);

        Datos.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos.getContentPane());
        Datos.getContentPane().setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(largoImg)
                    .addComponent(sizeShow)
                    .addComponent(anchoImg)
                    .addComponent(showName, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgName)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posXmosue)
                            .addComponent(showXmouse, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posYmouse)
                            .addComponent(showYmouse, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valRedImg)
                            .addComponent(showRedImg, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valGreenImg)
                            .addComponent(showGreenImg, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valBlueImg)
                            .addComponent(showBlueImg, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(sizeShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anchoImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(largoImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(showXmouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posXmosue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(showYmouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posYmouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(DatosLayout.createSequentialGroup()
                            .addComponent(showRedImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(valRedImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(showGreenImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valGreenImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(showBlueImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valBlueImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejo de Imagenes");
        setLocation(new java.awt.Point(120, 250));
        setMaximumSize(new java.awt.Dimension(950, 750));
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));

        labelImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelImg.setMaximumSize(new java.awt.Dimension(1200, 800));
        labelImg.setMinimumSize(new java.awt.Dimension(666, 419));
        labelImg.setName("labelImg"); // NOI18N

        Archivo.setText("Archivo");

        Cargar.setText("Cargar Imagen");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        Archivo.add(Cargar);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        barraMenu.add(Archivo);

        Editar.setText("Editar");
        barraMenu.add(Editar);

        Ver.setText("Ver");
        Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        datosWindow.setText("Datos");
        datosWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosWindowActionPerformed(evt);
            }
        });
        Ver.add(datosWindow);

        barraMenu.add(Ver);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 650, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelImg.getAccessibleContext().setAccessibleName("labelImg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        Buscar.setDialogTitle("Seleccionar Imagen");
        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagen :bmp, dib, gif,jpg, jpeg, jpe, jfif,png", "bmp", "dib", "gif",
                "jpg", "jpeg", "jpe", "jfif", "png");
        Buscar.setFileFilter(ext);

        if (Buscar.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            //rsscalelabel.RSScaleLabel.setScaleLabel(labelImg, Buscar.getSelectedFile().toString());
            
            //Image img=Toolkit.getDefaultToolkit().getImage(Buscar.getSelectedFile().toString()); 
            
            ImageIcon img= new ImageIcon(Buscar.getSelectedFile().getPath());
            
           /*
            int ancho = img.getIconWidth();
            int largo = img.getIconHeight();            
                      
            if (ancho > anchosc) {
                ancho = (int) (ancho * 0.75);
                if (largo > largosc) {
                    largo = (int) (largo * 0.75);
                }
            } else if (largo > largosc) {
                largo = (int) (largo * 0.75);
            } else {
                ancho = anchosc;
                largo = largosc;
            }
            
            labelImg.setSize(ancho, largo);       */     
  
            Icon icono= new ImageIcon(img.getImage().getScaledInstance(labelImg.getWidth(), labelImg.getHeight(), Image.SCALE_DEFAULT));            
            labelImg.setIcon(icono);
            
            this.repaint();

        }

    }//GEN-LAST:event_CargarActionPerformed

    private void sizeShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeShowActionPerformed

    private void Coord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Coord1ActionPerformed

    private void greenGrabber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenGrabber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenGrabber1ActionPerformed

    private void datosWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosWindowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datosWindowActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Cargar;
    private javax.swing.JCheckBoxMenuItem Coord1;
    private javax.swing.JInternalFrame Datos;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenu Histograma1;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Ver;
    private javax.swing.JMenu actionMenuDatos;
    private javax.swing.JTextField anchoImg;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JCheckBoxMenuItem blueGrabber1;
    private javax.swing.JCheckBoxMenuItem blueHist1;
    private javax.swing.JMenuItem datosWindow;
    private javax.swing.JMenu grabberOptn1;
    private javax.swing.JCheckBoxMenuItem greenGrabber1;
    private javax.swing.JCheckBoxMenuItem greenHist1;
    private javax.swing.JTextField imgName;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelImg;
    private javax.swing.JTextField largoImg;
    private javax.swing.JCheckBoxMenuItem nameOfImage1;
    private javax.swing.JTextField posXmosue;
    private javax.swing.JTextField posYmouse;
    private javax.swing.JCheckBoxMenuItem redGrabber1;
    private javax.swing.JCheckBoxMenuItem redHist1;
    private javax.swing.JTextField showBlueImg;
    private javax.swing.JTextField showGreenImg;
    private javax.swing.JTextField showName;
    private javax.swing.JTextField showRedImg;
    private javax.swing.JTextField showXmouse;
    private javax.swing.JTextField showYmouse;
    private javax.swing.JCheckBoxMenuItem sizeOfImage1;
    private javax.swing.JTextField sizeShow;
    private javax.swing.JTextField valBlueImg;
    private javax.swing.JTextField valGreenImg;
    private javax.swing.JTextField valRedImg;
    // End of variables declaration//GEN-END:variables

    
}


