/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.ColorModel;
import java.awt.image.PixelGrabber;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import manejoDatos.dameDatos;

/**
 *
 * @author zassu
 */
public class Panel extends javax.swing.JFrame {

    private final JFileChooser Buscar = new JFileChooser();
    private final Toolkit t = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private final int anchosc = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    private final int largosc = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    private final FrameDatos FrNvo = new FrameDatos();
    public  Icon bfImageglobal;
    private int X, Y, R, G, B, an, lar;
    public dameDatos datos = new dameDatos();

    public int getAn() {
        return an;
    }

    public void setAn(int an) {
        this.an = an;
    }

    public int getLar() {
        return lar;
    }

    public void setLar(int lar) {
        this.lar = lar;
    }

    public int getX() {
        return X;
    }

    public void setX(int X) {
        this.X = X;
    }

    public int getY() {
        return Y;
    }

    public void setY(int Y) {
        this.Y = Y;
    }

    public int getR() {
        return R;
    }

    public void setR(int R) {
        this.R = R;
    }

    public int getG() {
        return G;
    }

    public void setG(int G) {
        this.G = G;
    }

    public int getB() {
        return B;
    }

    public void setB(int B) {
        this.B = B;
    }

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        setExtendedState(NORMAL);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImg = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Cargar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        Ver = new javax.swing.JMenu();
        datosWindow = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejo de Imagenes");
        setLocation(new java.awt.Point(100, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));

        labelImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelImg.setMaximumSize(new java.awt.Dimension(1200, 800));
        labelImg.setMinimumSize(new java.awt.Dimension(666, 419));
        labelImg.setName("labelImg"); // NOI18N
        labelImg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelImgMouseMoved(evt);
            }
        });

        Archivo.setText("Archivo");

        Cargar.setText("Cargar Imagen");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        Archivo.add(Cargar);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        barraMenu.add(Archivo);

        Editar.setText("Editar");
        barraMenu.add(Editar);

        Ver.setText("Ver");
        Ver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        datosWindow.setText("Datos");
        datosWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosWindowActionPerformed(evt);
            }
        });
        Ver.add(datosWindow);

        barraMenu.add(Ver);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelImg.getAccessibleContext().setAccessibleName("labelImg");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        Buscar.setDialogTitle("Seleccionar Imagen");
        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagen :bmp, dib, gif,jpg, jpeg, jpe, jfif,png", "bmp", "dib", "gif",
                "jpg", "jpeg", "jpe", "jfif", "png");
        Buscar.setFileFilter(ext);

        if (Buscar.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            ImageIcon img = new ImageIcon(Buscar.getSelectedFile().getPath());
            bfImageglobal = new ImageIcon(img.getImage().getScaledInstance(labelImg.getWidth(), labelImg.getHeight(), Image.SCALE_SMOOTH));
            labelImg.setIcon(bfImageglobal);
            
            System.out.println(labelImg.getIcon().getIconWidth()+" "+labelImg.getIcon().getIconHeight());

            this.repaint();

            setAn(bfImageglobal.getIconWidth());
            setLar(bfImageglobal.getIconHeight());

            datos.setAncho(an);
            datos.setLargo(lar);

        }
        FrNvo.setDatos(teVanDatos(datos));
                
    }//GEN-LAST:event_CargarActionPerformed

    private void datosWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosWindowActionPerformed
        // TODO add your handling code here:

        FrNvo.setVisible(true);


    }//GEN-LAST:event_datosWindowActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void labelImgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImgMouseMoved
        // TODO add your handling code here:      
               ImageIcon imagen=new ImageIcon(Buscar.getSelectedFile().getPath());
               bfImageglobal= new ImageIcon(imagen.getImage().getScaledInstance(labelImg.getWidth(), labelImg.getHeight(), Image.SCALE_SMOOTH));
               ImageIcon nuevo= (ImageIcon) bfImageglobal;
        //imagen = Toolkit.getDefaultToolkit().getImage(Buscar.getSelectedFile().getPath());
     //   imagen=(Image) bfImageglobal;

        PixelGrabber Grabber = new PixelGrabber(nuevo.getImage(), evt.getX(), evt.getY(), labelImg.getIcon().getIconWidth(), labelImg.getIcon().getIconHeight(), true);

        try {
            if (Grabber.grabPixels()) {
                Object pixels = Grabber.getPixels();
                int red = ColorModel.getRGBdefault().getRed(pixels);
                int green = ColorModel.getRGBdefault().getGreen(pixels);
                int blue = ColorModel.getRGBdefault().getBlue(pixels);
                
                System.out.println(Grabber.getWidth()+" "+ Grabber.getHeight());
                

                setX(evt.getX());
                setY(evt.getY());
                setR(red);
                setG(green);
                setB(blue);
                
                

                datos.setCoodY(evt.getY());
                datos.setCoordX(evt.getX());
                datos.setPxgR(R);
                datos.setPxgG(G);
                datos.setPxgB(B);

                teVanDatos(datos);

                FrNvo.setDatos(teVanDatos(datos));
                
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
                FrNvo.getDatos().setEvt(evt);
        FrNvo.mouseMoved(FrNvo.getDatos().getEv());
    }//GEN-LAST:event_labelImgMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Cargar;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Ver;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem datosWindow;
    private javax.swing.JLabel labelImg;
    // End of variables declaration//GEN-END:variables

    public dameDatos teVanDatos(dameDatos dat) {

        dat.setNombre(Buscar.getSelectedFile().getName());
        dat.setCoordX(getX());
        dat.setCoodY(getY());
        dat.setPxgR(getR());
        dat.setPxgG(getG());
        dat.setPxgB(getB());
        dat.setAncho(getAn());
        dat.setLargo(getLar());

        return dat;
    }
}
